server:
  debugAddr: ":21211"
  httpAddr: ":21212"

postgres:
  uri: postgres://lid:@localhost:5432/lid?sslmode=disable
  maxIdle: 10
  maxOpen: 100

cache:
  useCache: true
  CacheExpire: 60
  CacheSize: 1024
